package com.shanks.fasalsaathi.models

data class Storage(
    val storageList : List<StorageItem>
)

data class StorageItem(
    val id: Int,
    val availability_duration: Int,
    val available: String,
    val available_from: String? = "2024-03-15",
    val capacity: Int,
    val contact: Long,
    val location: String,
    val name: String,
    val price: Int,
    val storage_image: String? = null,
    val storage_type: String
)

//val storageItems = listOf(
//    StorageItem(
//        id = 1,
//        availability_duration = 30,
//        available = true,
//        available_from = "2024-03-10",
//        capacity = 50,
//        contact = 1234567890,
//        location = "City A",
//        name = "City A Storage",
//        price = 100,
//        storage_image = "https://example.com/storage1.jpg",
//        storage_type = "Warehouse"
//    ),
//    StorageItem(
//        id = 2,
//        availability_duration = 60,
//        available = true,
//        available_from = "2024-03-15",
//        capacity = 100,
//        contact = 9876543210,
//        location = "City B",
//        name = "City B Storage",
//        price = 150,
//        storage_image = "https://example.com/storage2.jpg",
//        storage_type = "Garage"
//    ),
//    StorageItem(
//        id = 3,
//        availability_duration = 45,
//        available = true,
//        available_from = "2024-03-12",
//        capacity = 70,
//        contact = 1357924680,
//        location = "City C",
//        name = "City C Warehouse",
//        price = 120,
//        storage_image = "https://example.com/storage3.jpg",
//        storage_type = "Storage Unit"
//    ),
//    StorageItem(
//        id = 4,
//        availability_duration = 40,
//        available = true,
//        available_from = "2024-03-18",
//        capacity = 80,
//        contact = 2468013579,
//        location = "City D",
//        name = "City D Storage",
//        price = 200,
//        storage_image = "https://example.com/storage4.jpg",
//        storage_type = "Warehouse"
//    ),
//    StorageItem(
//        id = 5,
//        availability_duration = 55,
//        available = true,
//        available_from = "2024-03-20",
//        capacity = 90,
//        contact = 3692581470,
//        location = "City E",
//        name = "City E Garage",
//        price = 180,
//        storage_image = "https://example.com/storage5.jpg",
//        storage_type = "Garage"
//    ),
//    StorageItem(
//        id = 6,
//        availability_duration = 35,
//        available = true,
//        available_from = "2024-03-25",
//        capacity = 60,
//        contact = 1472583690,
//        location = "City F",
//        name = "City F Storage",
//        price = 130,
//        storage_image = "https://example.com/storage6.jpg",
//        storage_type = "Storage Unit"
//    ),
//    StorageItem(
//        id = 7,
//        availability_duration = 50,
//        available = true,
//        available_from = "2024-03-28",
//        capacity = 110,
//        contact = 2583691470,
//        location = "City G",
//        name = "City G Warehouse",
//        price = 220,
//        storage_image = "https://example.com/storage7.jpg",
//        storage_type = "Warehouse"
//    ),
//    StorageItem(
//        id = 8,
//        availability_duration = 65,
//        available = true,
//        available_from = "2024-04-01",
//        capacity = 120,
//        contact = 3691472580,
//        location = "City H",
//        name = "City H Storage",
//        price = 250,
//        storage_image = "https://example.com/storage8.jpg",
//        storage_type = "Garage"
//    ),
//    StorageItem(
//        id = 9,
//        availability_duration = 48,
//        available = true,
//        available_from = "2024-04-05",
//        capacity = 75,
//        contact = 9876543210,
//        location = "City I",
//        name = "City I Warehouse",
//        price = 190,
//        storage_image = "https://example.com/storage9.jpg",
//        storage_type = "Warehouse"
//    ),
//    StorageItem(
//        id = 10,
//        availability_duration = 42,
//        available = true,
//        available_from = "2024-04-08",
//        capacity = 85,
//        contact = 1234567890,
//        location = "City J",
//        name = "City J Garage",
//        price = 170,
//        storage_image = "https://example.com/storage10.jpg",
//        storage_type = "Garage"
//    ),
//    StorageItem(
//        id = 11,
//        availability_duration = 38,
//        available = true,
//        available_from = "2024-04-12",
//        capacity = 65,
//        contact = 3692581470,
//        location = "City K",
//        name = "City K Storage",
//        price = 140,
//        storage_image = "https://example.com/storage11.jpg",
//        storage_type = "Storage Unit"
//    ),
//    StorageItem(
//        id = 12,
//        availability_duration = 58,
//        available = true,
//        available_from = "2024-04-15",
//        capacity = 95,
//        contact = 1472583690,
//        location = "City L",
//        name = "City L Warehouse",
//        price = 230,
//        storage_image = "https://example.com/storage12.jpg",
//        storage_type = "Warehouse"
//    ),
//    StorageItem(
//        id = 13,
//        availability_duration = 47,
//        available = true,
//        available_from = "2024-04-18",
//        capacity = 100,
//        contact = 2583691470,
//        location = "City M",
//        name = "City M Storage",
//        price = 200,
//        storage_image = "https://example.com/storage13.jpg",
//        storage_type = "Garage"
//    ),
//    StorageItem(
//        id = 14,
//        availability_duration = 32,
//        available = true,
//        available_from = "2024-04-22",
//        capacity = 80,
//        contact = 3691472580,
//        location = "City N",
//        name = "City N Warehouse",
//        price = 180,
//        storage_image = "https://example.com/storage14.jpg",
//        storage_type = "Storage Unit"
//    ),
//    StorageItem(
//        id = 15,
//        availability_duration = 53,
//        available = true,
//        available_from = "2024-04-25",
//        capacity = 110,
//        contact = 9876543210,
//        location = "City O",
//        name = "City O Garage",
//        price = 250,
//        storage_image = "https://example.com/storage15.jpg",
//        storage_type = "Warehouse"
//    ),
//    StorageItem(
//        id = 16,
//        availability_duration = 36,
//        available = true,
//        available_from = "2024-04-28",
//        capacity = 90,
//        contact = 1234567890,
//        location = "City P",
//        name = "City P Storage",
//        price = 170,
//        storage_image = "https://example.com/storage16.jpg",
//        storage_type = "Garage"
//    ),
//    StorageItem(
//        id = 17,
//        availability_duration = 46,
//        available = true,
//        available_from = "2024-05-02",
//        capacity = 70,
//        contact = 3692581470,
//        location = "City Q",
//        name = "City Q Warehouse",
//        price = 150,
//        storage_image = "https://example.com/storage17.jpg",
//        storage_type = "Storage Unit"
//    ),
//    StorageItem(
//        id = 18,
//        availability_duration = 60,
//        available = true,
//        available_from = "2024-05-05",
//        capacity = 120,
//        contact = 1472583690,
//        location = "City R",
//        name = "City R Storage",
//        price = 270,
//        storage_image = "https://example.com/storage18.jpg",
//        storage_type = "Warehouse"
//    ),
//    StorageItem(
//        id = 19,
//        availability_duration = 39,
//        available = true,
//        available_from = "2024-05-08",
//        capacity = 100,
//        contact = 2583691470,
//        location = "City S",
//        name = "City S Garage",
//        price = 220,
//        storage_image = "https://example.com/storage19.jpg",
//        storage_type = "Garage"
//    ),
//    StorageItem(
//        id = 20,
//        availability_duration = 49,
//        available = true,
//        available_from = "2024-05-12",
//        capacity = 80,
//        contact = 3691472580,
//        location = "City T",
//        name = "City T Warehouse",
//        price = 190,
//        storage_image = "https://example.com/storage20.jpg",
//        storage_type = "Warehouse"
//    )
//)


